/*
 *     Generated by class-dump 3.3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import <Cocoa/Cocoa.h>

@class NSImage, NSMutableDictionary;

@interface AppleTMSettings : NSObject
{
    struct OpaqueCSBackupSettingsRef *_settings;
    struct OpaqueCSBackupPrefsRef *_prefs;
    BOOL _inited;
    NSMutableDictionary *_iconDictionary;
    NSImage *_timeMachineDiskIcon;
    NSImage *_genericDiskImage;
    NSImage *_networkVolumeImage;
    NSImage *_deleteImage;
}

+ (id)sharedSettings;
- (id)_UUIDForVolume:(id)arg1;
- (void)_addAliasData:(id)arg1 toKey:(struct __CFString *)arg2;
- (void)_addPath:(id)arg1 toKey:(struct __CFString *)arg2;
- (void)_addString:(id)arg1 toKey:(struct __CFString *)arg2;
- (BOOL)_isJobEnabled:(id)arg1;
- (id)_readArray:(struct __CFString *)arg1;
- (void)_removeAliasData:(id)arg1 fromKey:(struct __CFString *)arg2;
- (void)_removePath:(id)arg1 fromKey:(struct __CFString *)arg2;
- (void)_removeString:(id)arg1 fromKey:(struct __CFString *)arg2;
- (int)_setEnabled:(BOOL)arg1 forJob:(id)arg2 withAuthorization:(struct AuthorizationOpaqueRef *)arg3;
- (void)_setIsTimeMachineVolumePropertyTo:(struct __CFBoolean *)arg1 forMountPoint:(id)arg2;
- (void)_syncAndNotify;
- (void)_writeArray:(id)arg1 forKey:(id)arg2;
- (id)backupPath;
- (BOOL)canChangeWarningWhenCulling;
- (BOOL)canChooseBackupDevice;
- (BOOL)canEnableBackup;
- (BOOL)canManuallyBackup;
- (BOOL)canModifyBackupSet;
- (BOOL)canModifyRequiresACPower;
- (void)dealloc;
- (id)destinationDisplayName;
- (id)destinationIcon;
- (id)destinationServerDisplayName;
- (id)genericDiskIcon;
- (BOOL)hasDestination;
- (id)iconForPath:(id)arg1;
- (id)ignoredPaths;
- (id)includedVolumes;
- (id)init;
- (BOOL)isAutoBackupEnabled;
- (BOOL)isBackupDestinationReachable;
- (BOOL)isNetworkBackup;
- (long long)maxBackupSize;
- (id)networkVolumeIcon;
- (id)nextBackupDate;
- (BOOL)requiresACPower;
- (void)setAutoBackupEnabled:(BOOL)arg1 withAuthorization:(struct AuthorizationOpaqueRef *)arg2;
- (BOOL)setBackupPath:(id)arg1 error:(id *)arg2;
- (void)setMaxBackupSize:(long long)arg1;
- (void)setRequiresACPower:(BOOL)arg1;
- (void)setShowsWarningWhenCulling:(BOOL)arg1;
- (void)setSkipSystemFiles:(BOOL)arg1;
- (BOOL)showsWarningWhenCulling;
- (BOOL)skipItem:(id)arg1;
- (BOOL)skipSystemFiles;
- (id)skippedFolders;
- (id)skippedItems;
- (id)timeMachineDiskIcon;
- (BOOL)unskipItem:(id)arg1;
- (void)writeDefaults;

@end

