/*
 *     Generated by class-dump 3.3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableDictionary;

@interface BackupEngineStatus : NSObject
{
    NSMutableDictionary *_clients;
    int _clientsLock;
}

+ (id)sharedStatus;
- (void)clearPersistentStateForClient:(id)arg1;
- (id)clientStatus:(id)arg1;
- (void)dealloc;
- (id)init;
- (void)postNotifyString:(id)arg1;
- (void)sendNotify:(id)arg1;
- (void)updateClientStatus:(id)arg1;
- (void)updatePersistentStateForClient:(id)arg1 withValue:(id)arg2 forKey:(id)arg3;

@end

