/*
 *     Generated by class-dump 3.3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSOpenSavePanelDelegate-Protocol.h"

@class AddRemoveView, NSButton, NSMutableArray, NSMutableDictionary, NSMutableSet, NSOperationQueue, NSTableView, NSTextField, NSView, NSWindow, TMPreferencePane, TMSystemFilesSizerOperation, TMTotalIncludedSizerOperation;

@interface TMOptionsSheetController : NSObject <NSOpenSavePanelDelegate>
{
    TMPreferencePane *_preferencePane;
    NSWindow *_optionsSheet;
    NSTableView *_skippedItemsTableView;
    AddRemoveView *_addRemoveButtons;
    NSTextField *_totalIncludedTextField;
    NSButton *_warnCullingCheckbox;
    NSButton *_backupOnBatteryPowerCheckbox;
    NSButton *_showHiddenFilesCheckbox;
    NSView *_accessoryView;
    BOOL _skipSystemFiles;
    NSMutableArray *_skippedItems;
    NSMutableSet *_skippedItemsToRemove;
    NSMutableSet *_skippedItemsToAdd;
    NSMutableSet *_skippedItemsFAT;
    NSMutableSet *_skippedItemsExFAT;
    NSMutableDictionary *_cachedFolderSizes;
    NSOperationQueue *_sizerOperationQueue;
    TMSystemFilesSizerOperation *_systemFilesSizerOperation;
    TMTotalIncludedSizerOperation *_totalIncludedSizerOperation;
    BOOL _previousAutoBackupSetting;
}

- (long long)_sizeForPath:(id)arg1;
- (long long)_systemFilesSize;
- (void)addSkippedItemPressed:(id)arg1;
- (void)cancelPressed:(id)arg1;
- (void)dealloc;
- (void)donePressed:(id)arg1;
- (void)finalize;
- (void)helpPressed:(id)arg1;
- (void)loadNib;
- (long long)numberOfRowsInTableView:(id)arg1;
- (BOOL)panel:(id)arg1 shouldShowFilename:(id)arg2;
- (void)removeSkippedItemPressed:(id)arg1;
- (void)showHiddenFilesPressed:(id)arg1;
- (void)showOptionsSheet:(id)arg1;
- (void)showSkipSystemFilesAlert;
- (void)sizerOperationDidFail:(id)arg1;
- (void)sizerOperationDidSucceed:(id)arg1;
- (void)skipAddDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (BOOL)tableView:(id)arg1 acceptDrop:(id)arg2 row:(long long)arg3 dropOperation:(unsigned long long)arg4;
- (id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(long long)arg3;
- (BOOL)tableView:(id)arg1 shouldSelectRow:(long long)arg2;
- (id)tableView:(id)arg1 toolTipForCell:(id)arg2 rect:(struct CGRect *)arg3 tableColumn:(id)arg4 row:(long long)arg5 mouseLocation:(struct CGPoint)arg6;
- (unsigned long long)tableView:(id)arg1 validateDrop:(id)arg2 proposedRow:(long long)arg3 proposedDropOperation:(unsigned long long)arg4;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3 row:(long long)arg4;
- (void)tableViewSelectionDidChange:(id)arg1;
- (void)updateAddRemoveButtons;
- (void)updateTableViewContents;
- (void)updateTotalIncluded;
- (void)volumesChangedNotification:(id)arg1;

@end

