/*
 *     Generated by class-dump 3.3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

//#import "NSAdminPreference.h"
#import <PreferencePanes/PreferencePanes.h>

@class NSAlert, NSButton, NSImage, NSImageView, NSProgressIndicator, NSTabView, NSTextField, NSTimer, TMDateFormatter, TMDestinationSheetController, TMOnOffButton, TMOptionsSheetController, TMRolloverButton, TMSliderView, TMSystemBackup;

//@interface TMPreferencePane : NSAdminPreference
@interface TMPreferencePane : NSPreferencePane
{
    NSImageView *_timeMachineGraphicImageView;
    NSImageView *_chooseDestinationImageView;
    NSTabView *_tabView;
    TMSliderView *_onOffSliderView;
    TMOnOffButton *_onButton;
    TMOnOffButton *_offButton;
    NSButton *_changeDiskButton;
    NSButton *_optionsButton;
    NSButton *_chooseDiskButton;
    NSButton *_stopButton;
    TMRolloverButton *_errorInfoButton;
    NSButton *_helpButton;
    NSButton *_menuExtraCheckbox;
    NSTextField *_destinationNameTextField;
    NSTextField *_destinationNameLabelTextField;
    NSTextField *_destinationServerTextField;
    NSImageView *_destinationIconImageView;
    NSTextField *_availableSpaceTextField;
    NSTextField *_oldestBackupTextField;
    NSTextField *_latestBackupTextField;
    NSTextField *_nextBackupTextField;
    NSTextField *_nextBackupLabelTextField;
    NSTextField *_progressTextField;
    NSProgressIndicator *_progressIndicator;
    TMDestinationSheetController *_destinationSheetController;
    TMOptionsSheetController *_optionsSheetController;
    NSTimer *_updateAvailableSpaceTimer;
    NSTimer *_updateNextBackupDateTimer;
    NSTimer *_updateAtMidnightTimer;
    NSTimer *_restartCountdownTimer;
    double _restartInterval;
    TMDateFormatter *_dateFormatter;
    NSAlert *_errorAlert;
    NSImage *_timeMachinePrefPaneIcon;
    TMSystemBackup *_systemBackup;
    struct __CFRunLoopSource *_powerChangeRunLoopSource;
    double _originalDestinationNameTextFieldOffset;
}

- (void)_errorAlertDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)_setAutoBackupState:(long long)arg1;
- (BOOL)_updateTextField:(id)arg1 withStringValue:(id)arg2;
- (void)applicationDidBecomeActive:(id)arg1;
- (struct AuthorizationOpaqueRef *)authorization;
- (void)backupProgressDidChange:(id)arg1;
- (void)cancelRestartCountdown;
- (void)dealloc;
- (void)errorInfoPressed:(id)arg1;
- (void)finalize;
- (void)handleAppleEventWithData:(id)arg1;
- (void)handleOpenParameter:(const struct AEDesc *)arg1;
- (BOOL)hasBattery;
- (void)helpPressed:(id)arg1;
- (void)initiateRestartCountdown;
- (BOOL)isOnBattery;
- (void)machineDidWake:(id)arg1;
- (void)mainViewDidLoad;
- (void)menuExtraChangedNotification:(id)arg1;
- (void)menuExtraCheckboxPressed:(id)arg1;
- (void)offPressed:(id)arg1;
- (void)onOffSliderPressed:(id)arg1;
- (void)onPressed:(id)arg1;
- (void)pauseRestartCountdown;
- (void)prefsChanged:(id)arg1;
- (void)reflectEditableState;
- (void)restartCountdownTimerFired:(id)arg1;
- (void)resumeRestartCountdown;
- (void)showHelpAnchor:(id)arg1;
- (void)stopPressed:(id)arg1;
- (id)systemBackup;
- (id)timeMachinePrefPaneIcon;
- (void)updateAtMidnightTimerFired:(id)arg1;
- (void)updateAutoBackupGUI;
- (void)updateAvailableSpaceGUI;
- (void)updateAvailableSpaceTimerFired:(id)arg1;
- (void)updateBackupDestinationGUI;
- (void)updateGUI;
- (void)updateLatestBackupGUI;
- (void)updateMenuExtraGUI;
- (void)updateNextBackupDateTimerFired:(id)arg1;
- (void)updateNextBackupGUI;
- (void)updateOldestBackupGUI;
- (void)volumesChangedNotification:(id)arg1;
- (void)willSelect;
- (void)willUnselect;
- (void)windowWillClose:(id)arg1;

@end

