/*
 *     Generated by class-dump 3.3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import <Cocoa/Cocoa.h>

@class TMSlider;

@interface TMSliderView : NSView
{
    TMSlider *_slider;
    id _target;
    SEL _selector;
}

- (void)forwardInvocation:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
- (void)setAction:(SEL)arg1;
- (void)setEnabled:(BOOL)arg1;
- (void)setState:(long long)arg1;
- (void)setState:(long long)arg1 animate:(BOOL)arg2;
- (void)setTarget:(id)arg1;
- (id)slider;
- (long long)state;

@end

