/*
 *     Generated by class-dump 3.3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class NSDictionary;

@interface TMSystemBackup : NSObject
{
    struct OpaqueCSBackupServerProxyRef *_serverProxy;
    struct OpaqueCSBackupServerProxyRef *_statusProxy;
    struct __CFMachPort *_notifyPort;
    struct __CFRunLoopSource *_notifySource;
    id _delegate;
    int _daemonState;
    long long _bytesCompleted;
    long long _totalBytes;
    double _percentDone;
    unsigned long long _timeRemaining;
    unsigned long long _numberOfChangedItems;
    unsigned long long _numberOfExcludedItems;
    unsigned long long _numberOfDeepScannedItems;
    NSDictionary *_backupdStatesDictionary;
    int _updateLock;
    int _notifyToken;
}

- (int)_backupdStateFromStatusDictionary:(id)arg1;
- (BOOL)_isBackupdRunning;
- (void)_updateFromStatusDictionary:(id)arg1;
- (BOOL)backupInProgress;
- (void)backupNow:(id)arg1;
- (long long)bytesCompleted;
- (int)daemonState;
- (id)dateOfLastSuccessfulBackup;
- (id)dateOfOldestBackup;
- (void)dealloc;
- (id)delegate;
- (void)finalize;
- (id)init;
- (id)localizedStringFromValue:(id)arg1;
- (id)longErrorMessage;
- (unsigned long long)numberOfChangedItems;
- (unsigned long long)numberOfDeepScannedItems;
- (unsigned long long)numberOfExcludedItems;
- (double)percentDone;
- (BOOL)performHealthCheck:(id)arg1;
- (int)previousBackupResultCode;
- (id)resultDictionary;
- (BOOL)reuseBackup:(id)arg1;
- (void)serverDied:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setNeedsRescan;
- (id)shortErrorMessage;
- (void)stopBackingUp;
- (unsigned long long)timeRemaining;
- (long long)totalBytes;
- (void)updateProgress;

@end

